### ISSUE TITLE
new Help ->Report Bug or Enhancement

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1101]
This started showing up in my product:
from Help ->Report Bug or Enhancement
and has an error on start-up

``` ruby
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin.start() of bundle org.eclipse.mylyn.tasks.ui.
    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
    at org.eclipse.osgi.container.Module.start(Module.java:439)
    at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
    at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
    ... 210 more
Caused by: java.lang.StackOverflowError
    at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
    at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:58)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277)
    at org.apache.log4j.Category.<init>(Category.java:56)
    at org.apache.log4j.Logger.<init>(Logger.java:36)
```

I like it, maybe i should hook it up to something, ... but right now, it going nowhere is problematic.

**Comment by kasemir** [comment]
I don't see it in the SNS product.
