### ISSUE TITLE
PVTable Export to excel Java.time.format.DateTimeParseException 

### ISSUE THREAD

**Issue by utzeln** [ControlSystemStudio/cs-studio#1934]
Java.time.format.DateTimeParseException: Text '2016-10-21 14:28:55.023605801' could not be parsed: Unable to obtain ZonedDateTime from TemporalAccessor: {},ISO resolved to 2016-10-21T14:28:55.023605801 of type java.time.format.Parsed
	at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)
	at org.csstudio.display.pvtable.model.TimestampHelper.parse(TimestampHelper.java:61)
	at org.csstudio.display.pvtable.ui.ExportXLSAction.run(ExportXLSAction.java:275)

**Comment by kasemir** [comment]
I'll look at it, must be another quirk introduced when we moved to the Java 8 Instant.
