### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/cs-studio#2036]
Hello all,

when I run my version of CSS from Eclipse I always have the following exception. Have you an idea of ho to get rid of it?

```
Jan 12, 2017 1:21:18 PM org.csstudio.diirt.util.Activator start
INFO: Starting diirt.util
Jan 12, 2017 1:21:18 PM org.csstudio.diirt.util.RegisterDatasource registerDatasource
INFO: register Datasource:beast
Jan 12, 2017 1:21:18 PM org.diirt.util.config.Configuration getFile
INFO: Loading /Users/claudiorosati/.diirt/datasources/datasources.xml
Found bundle org.diirt.datasource_3.1.6.20161220162618 [9840]
Found bundle org.eclipse.osgi.internal.framework.BundleContextImpl@1e21a506
Found bundles [Lorg.osgi.framework.Bundle;@4ecd5134
Found bundleentry://9842.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.datasource-file_3.1.6.20161220162614 [9842]
Providers [org.diirt.datasource.file.FileDataSourceProvider]
Provider instance org.diirt.datasource.file.FileDataSourceProvider@7a599958
Found bundleentry://9846.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.datasource-loc_3.1.6.20161220162614 [9846]
Providers [org.diirt.datasource.loc.LocalDataSourceProvider]
Provider instance org.diirt.datasource.loc.LocalDataSourceProvider@7bbb1afb
Found bundleentry://9848.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.datasource-sim_3.1.6.20161220162614 [9848]
Providers [org.diirt.datasource.sim.SimulationDataSourceProvider]
Provider instance org.diirt.datasource.sim.SimulationDataSourceProvider@461032d8
Found bundleentry://9849.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.datasource-sys_3.1.6.20161220162614 [9849]
Providers [org.diirt.datasource.sys.SystemDataSourceProvider]
Provider instance org.diirt.datasource.sys.SystemDataSourceProvider@9f7e4ac
Found bundleentry://9857.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.support.diirt-ca_3.1.6.20161220162617 [9857]
Providers [org.diirt.support.ca.JCADataSourceProvider]
Provider instance org.diirt.support.ca.JCADataSourceProvider@b36aaff
Found bundleentry://9859.fwk1934692470/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.support.diirt-pva_3.1.6.20161220162618 [9859]
Providers [org.diirt.support.pva.PVADataSourceProvider]
Provider instance org.diirt.support.pva.PVADataSourceProvider@6723f888
!SESSION 2017-01-12 13:21:17.182 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product se.ess.ics.csstudio.product.product
Command-line arguments:  -product se.ess.ics.csstudio.product.product -data /Users/claudiorosati/Projects/Eclipse/workspaces/cs-studio/../runtime-cs-studio-ess.product -dev file:/Users/claudiorosati/Projects/Eclipse/workspaces/cs-studio/.metadata/.plugins/org.eclipse.pde.core/cs-studio-ess.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -data @user.home/.ess-cs-studio

!ENTRY org.eclipse.equinox.ds 1 0 2017-01-12 13:21:18.240
!MESSAGE Could not bind a reference of component org.csstudio.diirt.util.RegisterFormulaFunctionSet. The reference is: Reference[name = FormulaFunctionSet, interface = org.diirt.datasource.formula.FormulaFunctionSet, policy = dynamic, cardinality = 0..n, target = null, bind = registerFormulaFunctionSet, unbind = deregisterFormulaFunctionSet]

!ENTRY org.eclipse.equinox.ds 1 0 2017-01-12 13:21:18.243
!MESSAGE Could not bind a reference of component org.csstudio.diirt.util.RegisterService. The reference is: Reference[name = ServiceProvider, interface = org.diirt.service.ServiceProvider, policy = static, cardinality = 0..n, target = null, bind = registerService, unbind = null]
java.nio.file.NoSuchFileException: logs/CSSLogFile.0.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:402)
	at org.csstudio.logging.LogConfigurator.configureFileLogging(LogConfigurator.java:114)
	at org.csstudio.logging.LogConfigurator.configureFromPreferences(LogConfigurator.java:56)
	at org.csstudio.utility.product.Workbench.runWorkbench(Workbench.java:90)
	at org.csstudio.startup.application.Application.startApplication(Application.java:265)
	at org.csstudio.startup.application.Application.start(Application.java:119)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
2017-01-12 13:21:19.868 INFO [Thread 22] org.csstudio.security.authentication.UnattendedCallbackHandler (handleText) - OK
...
```

**Comment by shroffk** [comment]
The logging plugin is trying to use file logging but the folder to which it is supposed to write to "logs" does not exist

based on the preferences in the o.c.logging plugin, you should just leave an empty pattern and that should get rid of the error
```
# Path and pattern for log files
# Leave empty to disable file logging
file_pattern=
```
