### ISSUE TITLE
diirt CA crashes pcaspy server with 'long strings'

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#2045]
Example Python-based (pcaspy) CA server:
```
# longstring.py
from pcaspy import SimpleServer, Driver

prefix = 'TEST:'
pvdb = { 'TEXT' : { 'type' : 'char', 'count': 400  } }

class Example(Driver):
    def __init__(self):
        super(Example, self).__init__()
        self.setParam('TEXT', 'This is a test')
        
server = SimpleServer()
server.createPV(prefix, pvdb)
driver = Example()

while True:
    server.process(0.1)
```

One can access the "TEST:TEXT" PV with `caget`, `caget -S`, EPICS PV Tree, BOY using vtype.pv.

But accessing the PV with Probe or BOY using pvmanager results in a core dump of the CA server with this stack trace:

```
Core was generated by `python longstring.py'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fb5e6320846 in memcpy () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install python-2.6.6-66.el6_8.x86_64
(gdb) bt
#0  0x00007fb5e6320846 in memcpy () from /lib64/libc.so.6
#1  0x00007fb5df8b4141 in aitConvertFloat64Float64 (d=0x10ec390, s=0x0, c=1) at ../O.Common/aitConvertGenerated.cc:2835
#2  0x00007fb5dfd91d96 in aitConvert (desttype=aitEnumFloat64, dest=0x10ec390, srctype=aitEnumFloat64, src=0x0, count=1, pEnumStringTable=0x1108478)
    at ../../../../include/aitConvert.h:72
#3  0x00007fb5df8b783e in mapGddToDouble (vd=0x10ec390, count=1, dd=..., enumStringTable=...) at ../dbMapper.cc:452
#4  0x00007fb5df8bc7ee in mapControlGddToDouble (v=0x10ec340, count=1, dd=..., enumStringTable=...) at ../dbMapper.cc:1504
#5  0x00007fb5dfd8cf39 in casStrmClient::readNotifyResponse (this=0x1128670, guard=..., pChan=0x1128950, msg=..., desc=..., completionStatus=0)
    at ../../../../src/cas/generic/casStrmClient.cc:685
#6  0x00007fb5dfd8ccf7 in casStrmClient::readNotifyAction (this=0x1128670, guard=...) at ../../../../src/cas/generic/casStrmClient.cc:627
#7  0x00007fb5dfd8bdfd in casStrmClient::processMsg (this=0x1128670) at ../../../../src/cas/generic/casStrmClient.cc:251
#8  0x00007fb5dfda1b1a in casStreamOS::recvCB (this=0x1128670) at ../../../../src/cas/generic/st/casStreamOS.cc:463
#9  0x00007fb5dfda1a4a in casStreamReadReg::callBack (this=0x110ab40) at ../../../../src/cas/generic/st/casStreamOS.cc:428
#10 0x00007fb5df6583b4 in fdManager::process (this=0x7fb5df892600, delay=0.10000000000000001) at ../../../src/libCom/fdmgr/fdManager.cpp:162
#11 0x00007fb5e01e4af7 in _wrap_process (args=<value optimized out>) at pcaspy/casdef_wrap.cpp:10822
#12 0x00007fb5e6fa89d4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#13 0x00007fb5e6fa9b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#14 0x00007fb5e6faa647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#15 0x00007fb5e6faa722 in PyEval_EvalCode () from /usr/lib64/libpython2.6.so.1.0
#16 0x00007fb5e6fc4b9c in ?? () from /usr/lib64/libpython2.6.so.1.0
#17 0x00007fb5e6fc4c70 in PyRun_FileExFlags () from /usr/lib64/libpython2.6.so.1.0
#18 0x00007fb5e6fc615c in PyRun_SimpleFileExFlags () from /usr/lib64/libpython2.6.so.1.0
#19 0x00007fb5e6fd2892 in Py_Main () from /usr/lib64/libpython2.6.so.1.0
#20 0x00007fb5e62b5d1d in __libc_start_main () from /lib64/libc.so.6
#21 0x0000000000400649 in _start ()
```

This is with pcaspy 0.6.2, built for EPICS base 3.14.12.6,
and CSS using CAJ 1.1.15, JCA 2.3.6, diirt 3.1.6,
all on RedHat Enterprise Linux Workstation release 6.8.

**Comment by kasemir** [comment]
When using the older pcaspy 0.5.0, built for EPICS base 3.14.12.4, there is no crash.

The update to pcaspy 0.6.2, build for EPICS base 3.14.12, allows use of variable size arrays, while the older pcaspy and EPICS base will always serve arrays at their full element count.

**Comment by kasemir** [comment]
Xiaoqiang pointed to https://github.com/paulscherrerinstitute/pcaspy/issues/26 as a possibly related issue and suggested trying pcaspy version tagged 0.6.3rc6.
It indeed no longer crashes, so closing this as not inherently being a bug in CS-Studio.
