### ISSUE TITLE
Invalid thread access in databrowser

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2292]
To reproduce:

* Open databrowser plot
* Right-click and select Inspect Samples
* Restart CS-Studio

On the restart, we get

```
2017-09-21 11:34:13.904 WARNING [Thread 36] org.diirt.util.concurrent.Executors$2 (execute) - Exception on the timer thread caused by a ValueListener
org.eclipse.swt.SWTException: Invalid thread access
        at org.eclipse.swt.SWT.error(SWT.java:4491)
        at org.eclipse.swt.SWT.error(SWT.java:4406)
        at org.eclipse.swt.SWT.error(SWT.java:4377)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:420)
        at org.eclipse.swt.widgets.Combo.getSelectionIndex(Combo.java:1087)
        at org.csstudio.trends.databrowser2.sampleview.SampleView.update(SampleView.java:327)
        at org.csstudio.trends.databrowser2.sampleview.SampleView.access$0(SampleView.java:305)
        at org.csstudio.trends.databrowser2.sampleview.SampleView$1.changedItemLook(SampleView.java:99)
        at org.csstudio.trends.databrowser2.model.Model.fireItemLookChanged(Model.java:937)
        at org.csstudio.trends.databrowser2.model.ModelItem.fireItemLookChanged(ModelItem.java:198)
        at org.csstudio.trends.databrowser2.model.ModelItem.setUnits(ModelItem.java:169)
        at org.csstudio.trends.databrowser2.model.PVItem.updateUnits(PVItem.java:393)
        at org.csstudio.trends.databrowser2.model.PVItem.pvChanged(PVItem.java:380)
        at org.diirt.datasource.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
        at org.diirt.datasource.PVReaderImpl.setValue(PVReaderImpl.java:220)
        at org.diirt.datasource.PVDirector$4.run(PVDirector.java:358)
        at org.diirt.util.concurrent.Executors$2.execute(Executors.java:55)
        at org.diirt.datasource.PVDirector.notifyPv(PVDirector.java:323)
        at org.diirt.datasource.PVDirector.access$500(PVDirector.java:38)
        at org.diirt.datasource.PVDirector$6.desiredRateEvent(PVDirector.java:403)
        at org.diirt.datasource.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:168)
        at org.diirt.datasource.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by kasemir** [comment]
Same happens in databrowser3. Fixed in https://github.com/kasemir/org.csstudio.display.builder/commit/b46679692f5f3295c0e0784c2fcc151321292631
