### ISSUE TITLE
Frequent exception in databrowser from context menu

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2294]
I can't pin down exactly what is causing this, but frequently if I open a databrowser plot from the context menu (right click | Process Variable | Data Browser) I get the following exception:

```
2017-09-21 15:47:55.390 SEVERE [Thread 50] org.csstudio.logging.PluginLogListener (logging) - Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:483)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:421)
	at org.eclipse.swt.widgets.Widget.getData(Widget.java:509)
	at org.eclipse.ui.internal.ide.handlers.PagePropertyTester.test(PagePropertyTester.java:36)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:75)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateOr(CompositeExpression.java:68)
	at org.eclipse.core.internal.expressions.OrExpression.evaluate(OrExpression.java:22)
	at org.eclipse.core.internal.expressions.ReferenceExpression.evaluate(ReferenceExpression.java:71)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:72)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:97)
	at org.eclipse.ui.internal.services.EvaluationService.requestEvaluation(EvaluationService.java:294)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.update(DirtyStateTracker.java:45)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.propertyChanged(DirtyStateTracker.java:107)
	at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:120)
	at org.csstudio.trends.databrowser2.editor.DataBrowserEditor.setDirty(DataBrowserEditor.java:458)
	at org.csstudio.trends.databrowser2.editor.DataBrowserEditor$2.changedItemLook(DataBrowserEditor.java:255)
	at org.csstudio.trends.databrowser2.model.Model.fireItemLookChanged(Model.java:937)
	at org.csstudio.trends.databrowser2.model.ModelItem.fireItemLookChanged(ModelItem.java:198)
	at org.csstudio.trends.databrowser2.model.ModelItem.setUnits(ModelItem.java:169)
	at org.csstudio.trends.databrowser2.model.PVItem.updateUnits(PVItem.java:393)
	at org.csstudio.trends.databrowser2.model.PVItem.pvChanged(PVItem.java:380)
	at org.diirt.datasource.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.diirt.datasource.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.diirt.datasource.PVDirector$4.run(PVDirector.java:358)
	at org.diirt.util.concurrent.Executors$2.execute(Executors.java:55)
	at org.diirt.datasource.PVDirector.notifyPv(PVDirector.java:323)
	at org.diirt.datasource.PVDirector.access$500(PVDirector.java:38)
	at org.diirt.datasource.PVDirector$6.desiredRateEvent(PVDirector.java:403)
	at org.diirt.datasource.SourceDesiredRateDecoupler.sendDesiredRateEvent(SourceDesiredRateDecoupler.java:168)
	at org.diirt.datasource.PassiveScanDecoupler$1.run(PassiveScanDecoupler.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kasemir** [comment]
In DataBrowserEditor, the databrowser3 has this:
```
            @Override
            public void changedItemLook(final ModelItem item)
            {
                site.getShell().getDisplay().asyncExec(() -> setDirty(true));
            }
```

In comparison, databrowser2 calls setDirty directly, i.e. on the PV update thread, resulting in that error message.
