### ISSUE TITLE
Databrowser3 | org.csstudio.apputil.time : Cannot parse date and time

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2416]
I seem to be getting this error when opening "some" databrowser files.

```java
java.time.format.DateTimeParseException: Cannot parse date and time!
    at org.csstudio.apputil.time.AbsoluteTimeParser.parse(AbsoluteTimeParser.java:141)
    at org.csstudio.apputil.time.AbsoluteTimeParser.parse(AbsoluteTimeParser.java:72)
    at org.csstudio.apputil.time.StartEndTimeParser.<init>(StartEndTimeParser.java:76)
    at org.csstudio.trends.databrowser3.model.Model.setTimerange(Model.java:671)
    at org.csstudio.trends.databrowser3.persistence.XMLPersistence.load(XMLPersistence.java:163)
    at org.csstudio.trends.databrowser3.persistence.XMLPersistence.load(XMLPersistence.java:128)
    at org.csstudio.trends.databrowser3.editor.DataBrowserEditor.init(DataBrowserEditor.java:207)
    at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:318)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)

```

I'm guessing the issue is this part of the file:
```xml
<databrowser>
<title/>
<save_changes>true</save_changes>
<show_legend>false</show_legend>
<show_toolbar>true</show_toolbar>
<grid>false</grid>
<scroll>false</scroll>
<update_period>3.0</update_period>
<scroll_step>5</scroll_step>
<start>2018/02/03 09:00:00.000</start>
<end>2018/02/03 14:30:00.000</end>
...
```

**Comment by kasemir** [comment]
Yes, the absolute time format has changed, now using "-" instead of "/" in the date.

Will update the `XMLPersistence.load` to load older files.

**Comment by berryma4** [comment]
Thank you!
