### ISSUE TITLE
stacktraces when closing status opi screen

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2587]
I get one of these for every pv on the page (and there are a lot)

```java
Exception in thread "pool-5-thread-718" org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:526)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:612)
	at org.csstudio.opibuilder.properties.WidgetPropertyChangeListener.propertyChange(WidgetPropertyChangeListener.java:61)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at org.csstudio.opibuilder.properties.AbstractWidgetProperty.firePropertyChange(AbstractWidgetProperty.java:89)
	at org.csstudio.opibuilder.properties.AbstractWidgetProperty.setPropertyValue_IgnoreOldValue(AbstractWidgetProperty.java:209)
	at org.csstudio.opibuilder.editparts.PVWidgetEditpartDelegate$WidgetPVListener.valueChanged(PVWidgetEditpartDelegate.java:82)
	at org.csstudio.simplepv.pvmanager.PVManagerPV$3.pvChanged(PVManagerPV.java:231)
	at org.diirt.datasource.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.diirt.datasource.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.diirt.datasource.PVDirector$4.run(PVDirector.java:358)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "pool-5-thread-719" org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:526)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:612)
	at org.csstudio.opibuilder.properties.WidgetPropertyChangeListener.propertyChange(WidgetPropertyChangeListener.java:61)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at org.csstudio.opibuilder.properties.AbstractWidgetProperty.firePropertyChange(AbstractWidgetProperty.java:89)
	at org.csstudio.opibuilder.properties.AbstractWidgetProperty.setPropertyValue_IgnoreOldValue(AbstractWidgetProperty.java:209)
	at org.csstudio.opibuilder.editparts.PVWidgetEditpartDelegate$WidgetPVListener.valueChanged(PVWidgetEditpartDelegate.java:82)
	at org.csstudio.simplepv.pvmanager.PVManagerPV$3.pvChanged(PVManagerPV.java:231)
	at org.diirt.datasource.PVReaderImpl.firePvValueChanged(PVReaderImpl.java:110)
	at org.diirt.datasource.PVReaderImpl.setValue(PVReaderImpl.java:220)
	at org.diirt.datasource.PVDirector$4.run(PVDirector.java:358)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by berryma4** [comment]
I'm guessing it is a specific widget type, or how it is used, considering I only see this on our status screens.
