### ISSUE TITLE
PVTable: Restore 'Long' integers; Allow snapshot/restore for just the selected row; Show 'changed' rows even while selected

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#873]

**Comment by kasemir** [comment]
Reopening because there are more problems:

1) Loosing ability to edit after this happens:
```null at
	at org.eclipse.jface.viewers.TextCellEditor.doSetValue(TextCellEditor.java:231)
	at org.eclipse.jface.viewers.CellEditor.setValue(CellEditor.java:861)
	at org.eclipse.jface.viewers.EditingSupport.initializeCellEditorValue(EditingSupport.java:100)
	at org.eclipse.jface.viewers.ColumnViewerEditor.activateCellEditor(ColumnViewerEditor.java:199)
	at org.eclipse.jface.viewers.ColumnViewerEditor.handleEditorActivationEvent(ColumnViewerEditor.java:452)
	at org.eclipse.jface.viewers.ColumnViewer.triggerEditorActivationEvent(ColumnViewer.java:675)
	at org.eclipse.jface.viewers.ColumnViewer.handleMouseDown(ColumnViewer.java:650)
	at org.eclipse.jface.viewers.ColumnViewer.access$0(ColumnViewer.java:646)
	at org.eclipse.jface.viewers.ColumnViewer$1.mouseDown(ColumnViewer.java:95)
```

2) Long data still not written
